[package]
name = "json2toml"
version = "1.0.2"
authors = ["AtomXY <alexvd@inbox.ru>"]
edition = "2018"

[dependencies]
#serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.0"
serde_json = "1.0.59"

[[bin]]
name = "json2toml"
